### ISSUE TITLE
where nested object return Unknown argument

### ISSUE THREAD

**Issue by dwcahyo23** [nodeteamdev/nestjs-pipes#9]
how to input where arguments which are of type object?

**Comment by Vladyslav317** [comment]
Hi @dwcahyo23 ! Could you give an example?

If you want to use a 'where' clause with specific queries, you can write something like this:
`roles: hasSome array(string(VALUE)), email: string(VALUE)`

**Comment by dwcahyo23** [comment]
> Hi @dwcahyo23 ! Could you give an example?
> 
> If you want to use a 'where' clause with specific queries, you can write something like this: `roles: hasSome array(string(VALUE)), email: string(VALUE)`

Hi @Vladyslav317 , data schema like this, 
![image](https://github.com/nodeteamdev/nestjs-pipes/assets/101392599/d0bcecdd-9b17-439c-b277-933cf8746c12)
I tried to input the where argument :
`mstZ20.zCd: contains string(123)` but return 
Unknown_ argument `mstZ20.zCd`. Available options are marked with ?.

**Comment by dwcahyo23** [comment]
#11

I added new feat and has been tested with jest
